"""Вуд цфкурщгыу

Revision ID: b6e2b21e15c0
Revises: ef9d7c9787ec
Create Date: 2025-11-10 16:16:04.000747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e2b21e15c0'
down_revision: Union[str, Sequence[str], None] = 'ef9d7c9787ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shipment_items_shipment_id_fkey'), 'shipment_items', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_items', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shipments', 'warehouse_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.drop_constraint(op.f('shipments_warehouse_id_fkey'), 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key(op.f('shipments_warehouse_id_fkey'), 'shipments', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.alter_column('shipments', 'warehouse_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'shipment_items', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_items_shipment_id_fkey'), 'shipment_items', 'shipments', ['shipment_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
