"""initial migration

Revision ID: ef9d7c9787ec
Revises: 
Create Date: 2025-11-05 01:56:56.523251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9d7c9787ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict_at',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('depletion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depletion_at_p10', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depletion_at_p90', sa.DateTime(timezone=True), nullable=True),
    sa.Column('p_deplete_within', sa.Float(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predict_at_product_id'), 'predict_at', ['product_id'], unique=False)
    op.create_index(op.f('ix_predict_at_warehouse_id'), 'predict_at', ['warehouse_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('max_products', sa.Integer(), server_default='0', nullable=False),
    sa.Column('row_x', sa.Integer(), server_default='26', nullable=False),
    sa.Column('row_y', sa.Integer(), server_default='50', nullable=False),
    sa.Column('products_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('message1', sa.String(), nullable=True),
    sa.Column('message2', sa.String(), nullable=True),
    sa.Column('message3', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_id'), 'alarms', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'arrived', 'canceled', 'rescheduled', name='delivery_status', native_enum=False), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_delivered_at'), 'deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_deliveries_name'), 'deliveries', ['name'], unique=False)
    op.create_index(op.f('ix_deliveries_scheduled_at'), 'deliveries', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_deliveries_warehouse_id'), 'deliveries', ['warehouse_id'], unique=False)
    op.create_table('kkid_userid',
    sa.Column('kkid', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('kkid')
    )
    op.create_index(op.f('ix_kkid_userid_kkid'), 'kkid_userid', ['kkid'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='100', nullable=False),
    sa.Column('min_stock', sa.Integer(), server_default='20', nullable=False),
    sa.Column('optimal_stock', sa.Integer(), server_default='80', nullable=False),
    sa.Column('current_zone', sa.String(length=100), server_default='Хранение', nullable=False),
    sa.Column('current_row', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_shelf', sa.String(length=2), server_default='A', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ok', nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_last_scanned_at'), 'products', ['last_scanned_at'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('ix_products_wh_cell_lastscan', 'products', ['warehouse_id', 'current_row', 'current_shelf', 'last_scanned_at'], unique=False, postgresql_include=('id', 'name', 'category', 'article', 'stock', 'min_stock', 'optimal_stock'))
    op.create_index('ix_products_wh_name', 'products', ['warehouse_id', 'name'], unique=False)
    op.create_index('ix_products_wh_row_shelf', 'products', ['warehouse_id', 'current_row', 'current_shelf'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='idle', nullable=False),
    sa.Column('battery_level', sa.Integer(), server_default='100', nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_zone', sa.String(length=100), server_default='Хранение', nullable=False),
    sa.Column('current_row', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_shelf', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_robots_wh_status', 'robots', ['warehouse_id', 'status'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'shipped', 'canceled', 'rescheduled', name='shipment_status', native_enum=False), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_name'), 'shipments', ['name'], unique=False)
    op.create_index(op.f('ix_shipments_scheduled_at'), 'shipments', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_shipments_shipped_at'), 'shipments', ['shipped_at'], unique=False)
    op.create_table('delivery_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('fact_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_product_id'), 'delivery_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_warehouse_id'), 'delivery_items', ['warehouse_id'], unique=False)
    op.create_table('inventory_history',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('current_zone', sa.String(length=100), server_default='Хранение', nullable=False),
    sa.Column('current_row', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_shelf', sa.String(length=2), server_default='A', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('optimal_stock', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_hist_robot_created', 'inventory_history', ['robot_id', 'created_at'], unique=False)
    op.create_index('ix_inv_hist_wh_created', 'inventory_history', ['warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_inv_hist_wh_prod_created', 'inventory_history', ['warehouse_id', 'product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_created_at'), 'inventory_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_product_id'), 'inventory_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_robot_id'), 'inventory_history', ['robot_id'], unique=False)
    op.create_table('robot_history',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rh_robot_created', 'robot_history', ['robot_id', 'created_at'], unique=False)
    op.create_index('ix_rh_wh_created', 'robot_history', ['warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_rh_wh_status_created', 'robot_history', ['warehouse_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_robot_history_created_at'), 'robot_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_robot_history_robot_id'), 'robot_history', ['robot_id'], unique=False)
    op.create_table('scheduled_deliveries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_deliveries_product_id'), 'scheduled_deliveries', ['product_id'], unique=False)
    op.create_index(op.f('ix_scheduled_deliveries_scheduled_at'), 'scheduled_deliveries', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_deliveries_warehouse_id'), 'scheduled_deliveries', ['warehouse_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('fact_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_product_id'), 'shipment_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_warehouse_id'), 'shipment_items', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_items_warehouse_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_product_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_scheduled_deliveries_warehouse_id'), table_name='scheduled_deliveries')
    op.drop_index(op.f('ix_scheduled_deliveries_scheduled_at'), table_name='scheduled_deliveries')
    op.drop_index(op.f('ix_scheduled_deliveries_product_id'), table_name='scheduled_deliveries')
    op.drop_table('scheduled_deliveries')
    op.drop_index(op.f('ix_robot_history_robot_id'), table_name='robot_history')
    op.drop_index(op.f('ix_robot_history_created_at'), table_name='robot_history')
    op.drop_index('ix_rh_wh_status_created', table_name='robot_history')
    op.drop_index('ix_rh_wh_created', table_name='robot_history')
    op.drop_index('ix_rh_robot_created', table_name='robot_history')
    op.drop_table('robot_history')
    op.drop_index(op.f('ix_inventory_history_robot_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_product_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_created_at'), table_name='inventory_history')
    op.drop_index('ix_inv_hist_wh_prod_created', table_name='inventory_history')
    op.drop_index('ix_inv_hist_wh_created', table_name='inventory_history')
    op.drop_index('ix_inv_hist_robot_created', table_name='inventory_history')
    op.drop_table('inventory_history')
    op.drop_index(op.f('ix_delivery_items_warehouse_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_product_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_delivery_id'), table_name='delivery_items')
    op.drop_table('delivery_items')
    op.drop_index(op.f('ix_shipments_shipped_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_scheduled_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_name'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_robots_wh_status', table_name='robots')
    op.drop_table('robots')
    op.drop_index('ix_products_wh_row_shelf', table_name='products')
    op.drop_index('ix_products_wh_name', table_name='products')
    op.drop_index('ix_products_wh_cell_lastscan', table_name='products', postgresql_include=('id', 'name', 'category', 'article', 'stock', 'min_stock', 'optimal_stock'))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_last_scanned_at'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_kkid_userid_kkid'), table_name='kkid_userid')
    op.drop_table('kkid_userid')
    op.drop_index(op.f('ix_deliveries_warehouse_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_scheduled_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_name'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivered_at'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_alarms_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_predict_at_warehouse_id'), table_name='predict_at')
    op.drop_index(op.f('ix_predict_at_product_id'), table_name='predict_at')
    op.drop_table('predict_at')
    # ### end Alembic commands ###
