"""Atomic scheduled shipment; SQL adapter used by the synchronous scheduler."""

import logging
from collections import defaultdict
from datetime import datetime, timezone
from uuid import uuid4
from sqlalchemy import select
from sqlalchemy.orm import Session, raiseload
from backend.scheduler.config import Config
from backend.scheduler.locks import ten_minute_bucket, advisory_lock_key, acquire_lock
from backend.models.product import Product
from backend.models.warehouse import Warehouse
from backend.models.shipment import Shipment, ShipmentItems

log = logging.getLogger(__name__)


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


def run(session: Session, cfg: Config) -> None:
    ts = now_utc()
    bucket = ten_minute_bucket(ts)
    name = f"{cfg.shipment_name_prefix} {bucket}"
    # Never commit in finally: an exception must roll back the entire job.
    with session.begin():
        if not acquire_lock(session, advisory_lock_key("shipment_job_" + bucket)):
            return
        if session.scalar(select(Shipment.id).where(Shipment.name == name)):
            return
        products = list(
            session.scalars(
                select(Product)
                .options(raiseload("*"))
                .where(Product.stock > 0)
                .order_by(Product.id)
                .with_for_update(of=Product)
            )
        )
        if not products:
            return
        warehouse_ids = sorted({p.warehouse_id for p in products})
        warehouses = {
            w.id: w
            for w in session.scalars(
                select(Warehouse)
                .options(raiseload("*"))
                .where(Warehouse.id.in_(warehouse_ids))
                .order_by(Warehouse.id)
                .with_for_update()
            )
        }
        shipment = Shipment(
            id=str(uuid4()),
            name=name,
            warehouse_id=None,
            scheduled_at=ts,
            quantity=0,
            status=cfg.shipment_status,
            notes="Generated by scheduler",
        )
        session.add(shipment)
        session.flush()
        shipped = defaultdict(int)
        for product in products:
            quantity = min(max(1, cfg.item_qty_default), product.stock)
            session.add(
                ShipmentItems(
                    id=str(uuid4()),
                    shipment_id=shipment.id,
                    product_id=product.id,
                    warehouse_id=product.warehouse_id,
                    ordered_quantity=quantity,
                    fact_quantity=0,
                )
            )
            product.stock -= quantity
            shipped[product.warehouse_id] += quantity
            shipment.quantity += quantity
        for warehouse_id, quantity in shipped.items():
            warehouses[warehouse_id].products_count = max(
                0, warehouses[warehouse_id].products_count - quantity
            )
    log.info("Created scheduled shipment %s", name)
