import logging
import random
from uuid import uuid4
from typing import List, Optional, Iterable
from datetime import datetime, timezone, timedelta

from sqlalchemy import select, func
from sqlalchemy.orm import Session

from app.scheduler.config import Config
from app.scheduler.locks import (
    time_bucket,
    advisory_lock_key,
    acquire_lock,
    release_lock,
)
from app.models.product import Product
from app.models.shipment import Shipment, ShipmentItems
from app.models.delivery_items import DeliveryItems
from app.models.delivery import ScheduledDelivery, Delivery

log = logging.getLogger("scheduler.job")


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _to_int_safe(val: Optional[int], default: int = 0) -> int:
    try:
        return int(val) if val is not None else default
    except Exception:
        return default


def _resolve_warehouse_id(session: Session, cfg: Config, products: Iterable[Product]) -> str:
    """
    Выбираем warehouse_id для Shipment:
      1) если задан cfg.default_warehouse_id — используем его;
      2) иначе, если у всех выбранных товаров один и тот же warehouse_id — используем его;
      3) иначе — кидаем понятную ошибку (штатно прервём джобу).
    """
    if getattr(cfg, "default_warehouse_id", None):
        return cfg.default_warehouse_id

    uniq_wh = {getattr(p, "warehouse_id", None) for p in products}
    uniq_wh.discard(None)
    if len(uniq_wh) == 1:
        return next(iter(uniq_wh))

    raise RuntimeError(
        "Невозможно определить склад для Shipment: "
        "задайте cfg.default_warehouse_id или обеспечьте единый warehouse_id у выбранных товаров."
    )


def run(session: Session, cfg: Config) -> None:
    ts = now_utc()

    # 🧭 бакет строго по интервалу
    bucket_name = time_bucket(ts, cfg.interval_sec)

    # advisory-lock на это окно
    lock_key = advisory_lock_key(f"shipment_job_{bucket_name}")
    if not acquire_lock(session, lock_key):
        log.info("Уже выполняется для bucket=%s — выходим", bucket_name)
        return

    try:
        name = f"{cfg.shipment_name_prefix} {bucket_name}"

        # гарантируем «не больше 1 Shipment на окно»
        existing = session.execute(
            select(Shipment).where(Shipment.name == name)
        ).scalar_one_or_none()
        if existing:
            log.info("Shipment уже есть для bucket=%s (id=%s) — пропускаем", bucket_name, existing.id)
            # никакой commit не нужен — просто выходим, finally освободит лок
            return

        products: List[Product] = (
            session.execute(select(Product).where(Product.stock > 0))
            .scalars()
            .all()
        )
        if not products:
            log.info("Нет товаров с положительным остатком — пропускаем")
            return

        # КРИТИЧЕСКОЕ: получаем валидный warehouse_id
        try:
            shipment_wh_id = _resolve_warehouse_id(session, cfg, products)
        except Exception as e:
            log.error("Не удалось определить warehouse_id для shipment: %s — пропускаем окно", e)
            return

        shipment_id = str(uuid4())
        shipment = Shipment(
            id=shipment_id,
            name=name,
            warehouse_id=shipment_wh_id,  # <-- БОЛЬШЕ НЕ None
            scheduled_at=ts,
            shipped_at=None,
            quantity=0,
            status=cfg.shipment_status,
            customer=None,
            notes="Generated by scheduler",
        )

        try:
            session.add(shipment)
            # flush сразу, чтобы получить раннюю ошибку, если что-то не так
            session.flush()
        except Exception:
            # если тут упали — обязательно приводим сессию в порядок,
            # иначе release_lock ниже получит PendingRollbackError
            session.rollback()
            raise

        rows: List[ShipmentItems] = []
        total_qty = 0

        for p in products:
            # 1) Случайное списание 1..5
            desired = random.randint(1, 5)
            ordered_qty = min(desired, max(0, p.stock))
            if ordered_qty <= 0:
                continue

            # ShipmentItems (кладём warehouse_id от товара; сам Shipment — с общим wh)
            si = ShipmentItems(
                id=str(uuid4()),
                shipment_id=shipment_id,
                product_id=p.id,
                warehouse_id=getattr(p, "warehouse_id", shipment_wh_id),
                ordered_quantity=ordered_qty,
                fact_quantity=0,
            )
            rows.append(si)
            total_qty += ordered_qty

            # Снижаем stock (не уйдём в минус, т.к. min(...) выше)
            p.stock = p.stock - ordered_qty

            # 2) Проверяем триггер: достигли/перешли критическую отметку?
            current = _to_int_safe(p.stock)
            min_stock = _to_int_safe(getattr(p, "min_stock", None), default=0)
            optimal_stock = _to_int_safe(getattr(p, "optimal_stock", None), default=0)

            if current > min_stock:
                # запас ещё выше критического — ничего не заказываем
                continue

            # 3) Считаем, сколько не хватает до оптимума
            replenish_qty = max(0, optimal_stock - current)
            if replenish_qty <= 0:
                # уже и так оптимум/выше — не заказываем
                continue

            # 4) Не создаём дубли, если уже есть ожидаемая поставка по этому товару и складу
            wh_id = getattr(p, "warehouse_id", shipment_wh_id)
            pending = session.execute(
                select(func.count(ScheduledDelivery.id))
                .where(ScheduledDelivery.product_id == p.id)
                .where(ScheduledDelivery.warehouse_id == wh_id)
                .where(ScheduledDelivery.status == "scheduled")
            ).scalar()
            if pending and int(pending) > 0:
                log.info("Skip auto-replenish %s: pending scheduled delivery exists", p.id)
                continue

            # ---------- АВТО-ПОПОЛНЕНИЕ ДО OPTIMAL ----------
            # Планируем ScheduledDelivery на +4 минуты
            sd_id = str(uuid4())
            sd = ScheduledDelivery(
                id=sd_id,
                product_id=p.id,
                warehouse_id=wh_id,
                scheduled_at=ts + timedelta(minutes=4),  # задержка 4 минуты
                quantity=replenish_qty,                   # ⬅️ пополняем до оптимума
                status="scheduled",
                supplier="Auto replenish to optimal",
                notes=f"Replenish to optimal after shipment {shipment_id}",
            )
            session.add(sd)

            # Создаём DeliveryItems СЕЙЧАС, без родительского Delivery (delivery_id=None),
            di = DeliveryItems(
                id=f"{sd_id}_DI",
                delivery_id=None,  # ⬅️ привяжется материализатором
                product_id=p.id,
                warehouse_id=wh_id,
                ordered_quantity=replenish_qty,
                fact_quantity=0,
            )
            session.add(di)

            log.info(
                "Auto-replenish planned for product=%s: current=%d, min=%d, optimal=%d, order=%d",
                p.id, current, min_stock, optimal_stock, replenish_qty
            )
            # ------------------------------------------------

        if not rows:
            log.info("Все товары имели нулевой ordered_qty — отменяем создание")
            session.rollback()
            return

        # Сохраняем позиции и обновляем total
        session.add_all(rows)
        shipment.quantity = total_qty

        # Финальный commit транзакции создания shipment+items (+добавленные SD/DI)
        session.commit()

        log.info(
            "Создан shipment '%s' (id=%s) — позиций: %d, total_qty=%d",
            name, shipment_id, len(rows), total_qty
        )

    except Exception as e:
        # ВАЖНО: откатываемся, чтобы сессия вышла из failed state
        try:
            session.rollback()
        except Exception:
            pass
        log.exception("Create shipment failed: %s", e)

    finally:
        # Гарантируем чистое состояние перед release_lock
        try:
            # если вдруг кто-то оставил незавершённую транзакцию — аккуратно откатим
            session.rollback()
        except Exception:
            pass

        # Пытаемся освободить лок текущей сессией
        try:
            release_lock(session, lock_key)
            session.commit()
        except Exception:
            # Если сессия всё ещё не в порядке — освободим лок через новую сессию
            try:
                bind = session.get_bind()
                from sqlalchemy.orm import Session as _SyncSession  # локальный импорт, чтобы не путаться
                with _SyncSession(bind) as s2:
                    release_lock(s2, lock_key)
                    s2.commit()
            except Exception:
                log.exception("Не удалось освободить advisory lock (fallback тоже не сработал)")
